name: Deploy dev

on:
  workflow_dispatch:

jobs: 
  build-and-test:
    uses: ./.github/workflows/build-and-test-app.yaml
    with:
      path_to_upload_as_artifact: build
      upload_name: build

  deploy-app-to-dev:
    needs: [build-and-test]
    uses: ./.github/workflows/deploy-app-to-dev.yaml

  completed:
    needs: deploy-app-to-dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "Completed!"

    
    
