name: Build, test, upload
on:
  workflow_call:
    inputs:
      should_upload:
        required: false
        type: boolean
        default: false
      upload_name: 
        required: false
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create some files build dir
        run: |
          mkdir build

          mkdir build/jars
          echo "class" > build/jars/app.jar
          
          mkdir build/docs
          echo "doc file" > build/docs/doc-file.txt
          
          mkdir build
          echo "other file" > build/other-file.txt

      - name: Verify build dir
        run: |
          ls
          ls build
          ls build/jar
          ls build/docs

      - uses: actions/upload-artifact@v4.4.3
        if: inputs.should_upload
        with:
          name: ${{ inputs.upload_name }}
          path: |
            build/jars/
            build/docs/
          
