name: Build and test app
on:
  workflow_call:
    inputs:
      path_to_upload_as_artifact: 
        required: false
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir build
          echo "built file" >> build/built-file.txt
                  - name: Upload a Build Artifact
      - uses: actions/upload-artifact@v4.4.3
        if: inputs.upload_name != ""
        with:
          path: path_to_upload_as_artifact
          
