name: Deploy app to prod

on:
  workflow_call:
    inputs:
      artifact_name: 
        required: true
        type: string
      
jobs: 
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4.2.2

      - uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.artifact_name }}

      - name: Run it somehow
        run: less build/jars/app.jar

      - run: echo "Deployed to prod!"

    
