name: Deploy documentation

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string

jobs:
  deploy-documentation:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4.2.2

      - uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.artifact_name }}

      - name: Run it somehow
        run: less docs/doc-file.txt

      - run: echo "Deployed to documentation!"
