name: Deploy

on:
  push:
    branches: [main]

jobs: 
  build-and-test:
    uses: ./.github/workflows/build-and-test-app.yaml
    with:
      path_to_upload_as_artifact: build
      upload_name: build

  deploy:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4.2.2

      - uses: actions/download-artifact@v4.1.8
        with:
          name: build

      - name: Run it somehow
        run: less artifact/built-file.txt

      - name: Look at docs
        run: less artifact/docs/doc-file.txt

      - run: echo "Completed!"

    
    
