name: Deploy dev

on:
  workflow_dispatch:

jobs: 
  build-and-test:
    uses: ./.github/workflows/build-and-test-app.yaml
    with:
      path_to_upload_as_artifact: build
      upload_name: build

  deploy:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4.2.2

      - uses: actions/download-artifact@v4.1.8
        with:
          name: build
          path: build

      - name: Run it somehow
        run: less build/built-file.txt

      - run: echo "Completed!"

    
    
