name: Deploy to prod on push to master

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-test-upload.yaml
    with:
      should_upload: true
      upload_name: artifact

  deploy-to-dev:
    needs: [build-and-test]
    uses: ./.github/workflows/deploy-app-to-dev.yaml
    with: 
      artifact_name: artifact

  deploy-to-prod:
    needs: [deploy-to-dev]
    uses: ./.github/workflows/deploy-app-to-prod.yaml
    with: 
      artifact_name: artifact
